# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aefb40d0343a08c25e21f1c48a0b69eba3abc87c01e12c45e33df845eb3440be6552f65759b73a3c6aab59527d62d624f7be495c37b3d5b0db9e9a49345ea3ce

test:
  secret_key_base: 37356d2be6b45763e9d82ce0b8bc3b42ae4225463308d0a1c716f0702e653f283236322b34bf4ae3d23ebf0a62632f0d8300c78668fb22ad26e15980cc083c60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
